// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iTYzeKnrXvzQT22ANsbdfq
// Component: XQ76UUHPiG
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Ungroup from "../../Ungroup"; // plasmic-import: QJqxQ9Sc3N/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_jason_testing.module.css"; // plasmic-import: iTYzeKnrXvzQT22ANsbdfq/projectcss
import sty from "./PlasmicPage2.module.css"; // plasmic-import: XQ76UUHPiG/css

export type PlasmicPage2__VariantMembers = {};
export type PlasmicPage2__VariantsArgs = {};
type VariantPropType = keyof PlasmicPage2__VariantsArgs;
export const PlasmicPage2__VariantProps = new Array<VariantPropType>();

export type PlasmicPage2__ArgsType = {};
type ArgPropType = keyof PlasmicPage2__ArgsType;
export const PlasmicPage2__ArgProps = new Array<ArgPropType>();

export type PlasmicPage2__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
  ungroup?: p.Flex<typeof Ungroup>;
  link?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultPage2Props {}

function PlasmicPage2__RenderFunc(props: {
  variants: PlasmicPage2__VariantsArgs;
  args: PlasmicPage2__ArgsType;
  overrides: PlasmicPage2__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            {"PR please"}
          </div>

          <Ungroup
            data-plasmic-name={"ungroup"}
            data-plasmic-override={overrides.ungroup}
            className={classNames("__wab_instance", sty.ungroup)}
          />

          <p.PlasmicLink
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link
            )}
            component={Link}
            href={`/page-1/[id]`}
            platform={"nextjs"}
          >
            {"link"}
          </p.PlasmicLink>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text", "ungroup", "link"],
  text: ["text"],
  ungroup: ["ungroup"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
  ungroup: typeof Ungroup;
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPage2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPage2__VariantsArgs;
    args?: PlasmicPage2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPage2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPage2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPage2__ArgProps,
          internalVariantPropNames: PlasmicPage2__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicPage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPage2";
  } else {
    func.displayName = `PlasmicPage2.${nodeName}`;
  }
  return func;
}

export const PlasmicPage2 = Object.assign(
  // Top-level PlasmicPage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    ungroup: makeNodeComponent("ungroup"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicPage2
    internalVariantProps: PlasmicPage2__VariantProps,
    internalArgProps: PlasmicPage2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPage2;
/* prettier-ignore-end */
